package po;

public class CommentPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.upCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long upCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.downCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long downCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.postId
     *
     * @return the value of comment.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.postId
     *
     * @param postId the value for comment.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userId
     *
     * @return the value of comment.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userId
     *
     * @param userId the value for comment.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createdTime
     *
     * @return the value of comment.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createdTime
     *
     * @param createdTime the value for comment.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.upCount
     *
     * @return the value of comment.upCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUpCount() {
        return upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.upCount
     *
     * @param upCount the value for comment.upCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUpCount(Long upCount) {
        this.upCount = upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.downCount
     *
     * @return the value of comment.downCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getDownCount() {
        return downCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.downCount
     *
     * @param downCount the value for comment.downCount
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setDownCount(Long downCount) {
        this.downCount = downCount;
    }
}