package po;

public class FlashPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash.imagePath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String imagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash.id
     *
     * @return the value of flash.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash.id
     *
     * @param id the value for flash.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash.topicId
     *
     * @return the value of flash.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash.topicId
     *
     * @param topicId the value for flash.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash.imagePath
     *
     * @return the value of flash.imagePath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash.imagePath
     *
     * @param imagePath the value for flash.imagePath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
}