package po;

public class ForwardPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.lastUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long lastUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.id
     *
     * @return the value of forward.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.id
     *
     * @param id the value for forward.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.userId
     *
     * @return the value of forward.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.userId
     *
     * @param userId the value for forward.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.postId
     *
     * @return the value of forward.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.postId
     *
     * @param postId the value for forward.postId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.lastUserId
     *
     * @return the value of forward.lastUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getLastUserId() {
        return lastUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.lastUserId
     *
     * @param lastUserId the value for forward.lastUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setLastUserId(Long lastUserId) {
        this.lastUserId = lastUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.createdTime
     *
     * @return the value of forward.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.createdTime
     *
     * @param createdTime the value for forward.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }
}