package po;

public class MessagePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.srcUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long srcUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.desUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long desUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createdTime
     *
     * @return the value of message.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createdTime
     *
     * @param createdTime the value for message.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.srcUserId
     *
     * @return the value of message.srcUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getSrcUserId() {
        return srcUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.srcUserId
     *
     * @param srcUserId the value for message.srcUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setSrcUserId(Long srcUserId) {
        this.srcUserId = srcUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.desUserId
     *
     * @return the value of message.desUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getDesUserId() {
        return desUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.desUserId
     *
     * @param desUserId the value for message.desUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setDesUserId(Long desUserId) {
        this.desUserId = desUserId;
    }
}