package po;

public class PostPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.mediaPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String mediaPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.userId
     *
     * @return the value of post.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.userId
     *
     * @param userId the value for post.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.topicId
     *
     * @return the value of post.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.topicId
     *
     * @param topicId the value for post.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.createdTime
     *
     * @return the value of post.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.createdTime
     *
     * @param createdTime the value for post.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.mediaPath
     *
     * @return the value of post.mediaPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.mediaPath
     *
     * @param mediaPath the value for post.mediaPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}