package po;

public class TopicCarePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_care.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_care.lastAccessTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long lastAccessTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_care.id
     *
     * @return the value of topic_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_care.id
     *
     * @param id the value for topic_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_care.userId
     *
     * @return the value of topic_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_care.userId
     *
     * @param userId the value for topic_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_care.topicId
     *
     * @return the value of topic_care.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_care.topicId
     *
     * @param topicId the value for topic_care.topicId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_care.createdTime
     *
     * @return the value of topic_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_care.createdTime
     *
     * @param createdTime the value for topic_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_care.lastAccessTime
     *
     * @return the value of topic_care.lastAccessTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_care.lastAccessTime
     *
     * @param lastAccessTime the value for topic_care.lastAccessTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setLastAccessTime(Long lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
}