package po;

public class TopicPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.iconPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private String iconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.form
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Integer form;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.createdTime
     *
     * @return the value of topic.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.createdTime
     *
     * @param createdTime the value for topic.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.userId
     *
     * @return the value of topic.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.userId
     *
     * @param userId the value for topic.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.iconPath
     *
     * @return the value of topic.iconPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.iconPath
     *
     * @param iconPath the value for topic.iconPath
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.form
     *
     * @return the value of topic.form
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Integer getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.form
     *
     * @param form the value for topic.form
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setForm(Integer form) {
        this.form = form;
    }
}