package po;

public class UserCarePo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_care.caredUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long caredUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    private Long createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_care.id
     *
     * @return the value of user_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_care.id
     *
     * @param id the value for user_care.id
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_care.userId
     *
     * @return the value of user_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_care.userId
     *
     * @param userId the value for user_care.userId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_care.caredUserId
     *
     * @return the value of user_care.caredUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCaredUserId() {
        return caredUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_care.caredUserId
     *
     * @param caredUserId the value for user_care.caredUserId
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCaredUserId(Long caredUserId) {
        this.caredUserId = caredUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_care.createdTime
     *
     * @return the value of user_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_care.createdTime
     *
     * @param createdTime the value for user_care.createdTime
     *
     * @mbggenerated Thu Jun 02 14:14:38 CST 2016
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }
}